### ISSUE TITLE
Upgrade to  helm 3 

### ISSUE THREAD

**Issue by vuletuanbt** [ruzickap/k8s-flux-istio-gitlab-harbor#130]
Dear @ruzickap!
Your tutorial is fantastic and very helpful. E do follow your instruction but I got some issues:
 - Helm's v3 now, but in your tutorial is 2
 - Can not verify installation on your tech (istio, harbor) is working or not
I saw your channel on youtube, Some of your tutorials was recorded, so Can you make a new video tutorial for this tutorial?

**Comment by ruzickap** [comment]
Hello.

I'm glad it is "still" helpful. 

Unfortunately these tutorials are several years old and I doubt they have relevant information in these days (maybe only some parts).

I'm sorry, but I do not plan to update it.

**Comment by vuletuanbt** [comment]
@ruzickap Thanks for your quick response. May I ask one more question? Do you have any tech stack for GitLab and k8s combination

**Comment by ruzickap** [comment]
I also have this one: https://ruzickap.github.io/k8s-knative-gitlab-harbor/part-05/
It is quite old as well.
I'm no longer use GitLab...
